### ISSUE TITLE
Clean up `Initial Build`

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-cssource-freeplay#1]
Initial build of this server has been committed and is building properly in Docker Cloud. Please

- [x] Tweak server.cfg and any other server elements you like

- [x] Get MOTD going

- [x] Review tests under `./ll-tests/...` and add anything missing

**Comment by JustinBenedick** [comment]
All done with pull and commit 0501b042f5ac921fe7e7182da90f4dccfd0db4c, can't check any boxes

**Comment by dudleycodes** [comment]
@JustinBenedick - idk why you keep having issues w/ these checkboxes :/

Are all three of them complete?

**Comment by JustinBenedick** [comment]
Yep

**Comment by dudleycodes** [comment]
Closing
